FROM python:3.10-slim


RUN apt-get update && apt-get -y install \
    tesseract-ocr \
    tesseract-ocr-jpn \
    libgl1-mesa-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY . .


RUN pip install --upgrade pip && \
    pip install \
    pillow \
    pytesseract \
    -r requirements.txt


CMD ["celery", "-A", "second_dir.task.tasks", "worker", "--loglevel=INFO", "--pool=solo"]